### ISSUE TITLE
An error while model loading in web_demo.ipynb

### ISSUE THREAD

**Issue by SUSIEE01** [LukeJaffe/GFN#5] opened 2023-03-06 06:43 UTC
I’am trying to run the web_demo.ipynb but meet an error as follow.
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11836\3154094266.py in <module>
      1 # Load torchscript version of model
----> 2 model = torch.jit.load(torchscript_path)

c:\Users\SUSIE\Anaconda3\envs\osr\lib\site-packages\torch\jit\_serialization.py in load(f, map_location, _extra_files)
    160     cu = torch._C.CompilationUnit()
    161     if isinstance(f, str) or isinstance(f, pathlib.Path):
--> 162         cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
    163     else:
    164         cpp_module = torch._C.import_ir_module_from_buffer(

RuntimeError: 
Unknown builtin op: torchvision::roi_align.
Could not find any similar ops to torchvision::roi_align. This op may not exist or may not be currently supported in TorchScript.
:
  File "code/__torch__/torchvision/ops/roi_align.py", line 18
  else:
    rois = unchecked_cast(Tensor, boxes)
  _6 = ops.torchvision.roi_align(input, rois, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned)
       ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _6
'roi_align' is being compiled since it was called from '_multiscale_roi_align'
Serialized   File "code/__torch__/torchvision/ops/poolers.py", line 128
  _30 = "scales and mapper should not be None"
  _31 = __torch__.torchvision.ops.poolers._convert_to_roi_format
  _32 = __torch__.torchvision.ops.roi_align.roi_align
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  _33 = "This Python function is annotated to be ignored and cannot be run"
  _34 = uninitialized(Tensor)
'_multiscale_roi_align' is being compiled since it was called from 'MultiScaleRoIAlign.forward'
Serialized   File "code/__torch__/torchvision/ops/poolers.py", line 19
    _0 = __torch__.torchvision.ops.poolers._filter_input
    _1 = __torch__.torchvision.ops.poolers._setup_scales
    _2 = __torch__.torchvision.ops.poolers._multiscale_roi_align
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    featmap_names = self.featmap_names
    x_filtered = _0(x, featmap_names, )
```
![error](https://user-images.githubusercontent.com/90890796/223035715-ad00ec42-f1d8-47d5-94f7-a643720eb60b.png)

A similar problem ([https://stackoverflow.com/questions/65705160/torch-vision-c-interface-error-unknown-builtin-op-torchvisionnms](url)) was solved by replacing the torch version. I also read some related issue ([https://github.com/pytorch/vision/issues](url)) but I didn't find a solution.
My environment is pytorch=1.12.0 + torchvision=0.13.0 as yours in conda.yaml.

**Comment by LukeJaffe** [comment] 2023-03-06 19:33
Thanks for pointing this out. Try to add "import torchvision" at the top, and let me know if that works.

**Comment by SUSIEE01** [comment] 2023-03-07 01:14
It doesn't work...

**Comment by SUSIEE01** [comment] 2023-03-07 01:21
It doesn't work...

**Comment by LukeJaffe** [comment] 2023-03-07 02:37
I'm not sure, I'm unable to reproduce this with a clean version of the repo and environment. Did you activate your conda environment? If conda isn't working, you can also try the docker image.

**Comment by SUSIEE01** [comment] 2023-03-07 06:50
I had activated my conda environment. I will try docker later.

**Comment by LukeJaffe** [comment] 2023-03-23 23:35
Closing this for now. Let me know if there is a fix that is specific to your configuration.

**Closed** 2023-03-23 23:35 UTC
